import { DEBUG_RENDER_DIAGNOSTICS } from './diagnostics';

const SHOW_SPATIAL_OVERLAY = import.meta.env.DEV || DEBUG_RENDER_DIAGNOSTICS;

export const DEBUG_SPATIAL = SHOW_SPATIAL_OVERLAY;
export const DEBUG_SPATIAL_LOG = DEBUG_RENDER_DIAGNOSTICS;
export const DEBUG_SPATIAL_SHOW_CELL_COUNTS = SHOW_SPATIAL_OVERLAY;
export const SPATIAL_GRID_CELL_SIZE = 256;
export const DEBUG_MARQUEE_LOG = DEBUG_RENDER_DIAGNOSTICS;

// 压测时可临时改成 2000，默认关闭，不影响正常文档。
export const DEBUG_SPATIAL_STRESS_BOX_COUNT = 0;
