// 统一控制 canvas 上的调试可视化：HUD、视口红框、调试网格。
export const DEBUG_CANVAS_OVERLAY = false;
export const DEBUG_NEW_MIND_SEED_NODE_COUNT = DEBUG_CANVAS_OVERLAY ? 300 : 0;

export const DEBUG_SPATIAL = DEBUG_CANVAS_OVERLAY;
export const DEBUG_SPATIAL_LOG = DEBUG_CANVAS_OVERLAY;
export const DEBUG_SPATIAL_SHOW_CELL_COUNTS = DEBUG_CANVAS_OVERLAY;
export const SPATIAL_GRID_CELL_SIZE = 256;
export const DEBUG_MARQUEE_LOG = DEBUG_CANVAS_OVERLAY;

// 压测时可临时改成 2000，默认关闭，不影响正常文档。
export const DEBUG_SPATIAL_STRESS_BOX_COUNT = 0;
